# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'AVNotes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVNotes
pod 'Disk', '~> 0.3.3'
pod 'SwiftLint'
pod 'Firebase/Core'

end
