# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVNotes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVNotes
pod 'Disk', '~> 0.3.3'
#pod 'AudioKit/UI', '~> 4.0'
#pod 'AudioKit', '~> 4.0'

end
